import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import AppBar from "../components/AppBar";
import StoreProvider from "./storeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppBar/>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
